name_maximum: 50
email_maximun: 255
pass_minimun: 6
img_size: 80
random_function: "RAND()"
random_function_postgre: "RANDOM()"
number_list_anime: 10
menubar:
  version: "1.0"
  copy_right: "@JVSUB_TEAM"
appName: "AnimeJVSub"
movies_per_page: 8
users_per_page: 15

